### ISSUE TITLE
Remove the tight dependency on nvml native from building Mnemonic

### ISSUE THREAD

**Issue by umamaheswararao** [NonVolatileComputing/Mnemonic#1]
Currently, not able to proceed the build in MAC os due to the dependency on NVML. I can't build nvml in OSx.
So, it would be good to skip nvml default. when we want to include it we can mention explicitly in maven command that mvn ....... -Dnative-nvml

**Comment by AI-Memory** [comment]
The design could be use the SPI (Service Provider Interface) to decouple the allocators as Services (AaaS), therefore, developers is able to add more AaaS instances to support more memory-like devices for Mnemonic.

**Comment by AI-Memory** [comment]
this issue has been addressed
