### ISSUE TITLE
Java 7 does not have Element#getAnnotationByType

### ISSUE THREAD

**Issue by umamaheswararao** [NonVolatileComputing/Mnemonic#3]
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.3:compile (default-compile) on project mnemonic-core: Compilation failure: Compilation failure:
[ERROR] /home/max/Projects/mnemonic/m0/core/src/main/java/com/intel/bigdatamem/AnnotatedNonVolatileEntityClass.java:[236,68] cannot find symbol
[ERROR] symbol:   method getAnnotationsByType(java.lang.Class<com.intel.bigdatamem.NonVolatileGetter>)
[ERROR] location: variable elem of type javax.lang.model.element.Element
[ERROR] /home/max/Projects/mnemonic/m0/core/src/main/java/com/intel/bigdatamem/AnnotatedNonVolatileEntityClass.java:[242,49] cannot find symbol
[ERROR] symbol:   method getAnnotationsByType(java.lang.Class<com.intel.bigdatamem.NonVolatileSetter>)

**Comment by AI-Memory** [comment]
Yes It is true,  we will replaced it with "getAnnotation()" for compatibility, Thanks.
